{% set name = "verilator" %}
{% set version = "4.034" %}

package:
  name: verilator-packages
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 17a087fc74fd1ab035a43ba38d6f6198150ee11b20077855404ddb4c1620c6b7
  patches:
    - patches/0001-Use-usr-bin-env-perl-in-lieu-of-usr-bin-perl.patch
    - patches/0002-Fix-build-with-Bison-3.7-and-newer-2505.patch
    - patches/0003-Fix-missing-install-of-vl_file_copy-vl_hier_graph-31.patch
    - patches/0004-add-message-suggesting-verilator-debug-package.patch

build:
  number: 3
  skip: true  # [not (osx | linux64)]
  ignore_run_exports:
    - python
  #has_prefix_files:
  #- share/verilator/include/verilated.mk

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - make
    - bison
    - python   >=3
    - perl
    - sed
    - git # for patching
  host:
    - zlib
    - flex  # need to link against it for target
  run:
    - {{ compiler('cxx') }}  # [osx]
    # there must be a way to derive this from compiler('cxx') but this should work
    - gxx_impl_linux-64  # [linux64]
    - {{ pin_compatible('flex') }}
    - make
    - perl
  run_constrained:
    - python  >=3.5

# test requirements aren't supported in subpackages, so we run the tests
# on the metapackage
test:
  requires:
    - pkgconfig
    - cmake
    - python
    - graphviz
    # only need C compiler because cmake bails if it doesn't have one.
    # at least with the CMakeLists.txt in the examples
    - {{ compiler('c') }}
    # re-install the default compiler package with activation scripts
    # because it is the easiest way to get cmake to work in the sanity checks
    # for cmake.  However, normal makefile based tests do not need this and
    # will work fine because verilated.mk builds in the path 
    - {{ compiler('cxx') }}

outputs:
  - name: verilator
    script: install.sh
    requirements:
      build:
        - make
        - ripgrep
        - perl # avoid BSD sed weirdness
      host:
        - zlib
        - flex  # need to link against it for target
      run:
        - {{ compiler('cxx') }}  # [osx]
        # there must be a way to derive this from compiler('cxx') but this should work
        - gxx_impl_linux-64  # [linux64]
        - {{ pin_compatible('flex') }}
        - make
        - perl
      run_constrained:
        - python  >=3.5
  - name: verilator-debug
    script: install.sh
    requirements:
      run:
        - {{ pin_subpackage('verilator', exact=True) }}

about:
  home: https://veripool.org/wiki/verilator
  license: LGPL-3.0-only OR Artistic-2.0
  license_file:
    - LICENSE
    - Artistic
  summary: The fastest Verilog HDL simulator

  description: |
    Welcome to Verilator, the fastest Verilog HDL simulator.
      • Accepts synthesizable Verilog or SystemVerilog
      • Performs lint code-quality checks
      • Compiles into multithreaded C++, or SystemC
      • Creates XML to front-end your own tools
    Fast
      • Outperforms many commercial simulators
      • Single- and multi-threaded output models
    Widely Used
      • Wide industry and academic deployment
      • Out-of-the-box support from Arm, and RISC-V vendor IP
    Community Driven & Openly Licensed
      • Guided by the CHIPS Alliance and Linux Foundation
      • Open, and free as in both speech and beer
      • More simulation for your verification budget
    Commercial Support Available
      • Commercial support contracts
      • Design support contracts
      • Enhancement contracts
  doc_url: https://www.veripool.org/projects/verilator/wiki/Documentation
  dev_url: https://github.com/verilator/verilator

extra:
  recipe-maintainers:
    - timsnyder
